apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: cops-controller
  {{ if hasKey .Values "namespace" }}namespace: {{ .Values.namespace }}{{ end }}
spec:
  generateSelector: true
  parentResource:
    apiVersion: coreops.conplement.cloud/v1
    resource: copsnamespaces
  childResources:
  - apiVersion: v1
    resource: namespaces
    updateStrategy:
      method: InPlace
  - apiVersion: rbac.authorization.k8s.io/v1
    resource: rolebindings
    updateStrategy:
      method: InPlace
  hooks:
    sync:
      webhook:
        url: http://{{ template "cops-controller.name" . }}.{{ .Release.Namespace }}/api/sync