apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: hello-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: coreops.conplement.cloud/v1
    resource: copsnamespaces
  childResources:
  - apiVersion: v1
    resource: namespaces
    updateStrategy:
      method: InPlace
  hooks:
    sync:
      webhook:
        url: http://{{ template "cops-controller.name" . }}.{{ .Release.Namespace }}/api/sync