# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
name: $(imageName)

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  dockerId: conplementag
  imageBaseName: cops-controller
  imageName: '$(imageBaseName):$(build.buildNumber)-dev'

steps:
- script: |
    docker build -t $(dockerId)/$(imageName) .
    docker login -u $(dockerUsername) -p $(dockerPassword)
    docker push $(dockerId)/$(imageName)

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.SourcesDirectory)/deployment/cops-controller' 
    artifactName: 'cops-controller' 