# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
name: $(imageName)

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  dockerId: conplementag
  imageBaseName: cops-controller
  imageName: '$(imageBaseName):$(build.buildNumber)-dev'

steps:
- script: |
    docker login -u $(dockerUsername) -p $(dockerPassword)
    docker build -t $(dockerId)/$(imageName) .
  displayName: Build

- script: |
    docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/Library/Caches:/root/.cache/ aquasec/trivy --exit-code 0 --severity MEDIUM,HIGH --ignore-unfixed $(dockerId)/$(imageName)
    docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/Library/Caches:/root/.cache/ aquasec/trivy --exit-code 1 --severity CRITICAL --ignore-unfixed $(dockerId)/$(imageName)
  displayName: Scan

- script: |
    docker push $(dockerId)/$(imageName)
  displayName: Push

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.SourcesDirectory)/deployment/cops-controller' 
    artifactName: 'cops-controller' 