kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: copsnamespace-creator
rules:
- apiGroups: ["coreops.conplement.cloud"]
  resources: ["copsnamespaces"]
  verbs: ["get", "list", "create"]