apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "cops-controller.name" . }}
  {{ if hasKey .Release "namespace" }}namespace: {{ .Release.namespace }}{{ end }}
  labels:
    app: {{ template "cops-controller.name" . }}
    chart: {{ template "cops-controller.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "cops-controller.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "cops-controller.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP