apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: copsnamespaces.coreops.conplement.cloud
spec:
  group: coreops.conplement.cloud
  version: v1
  scope: Cluster
  names:
    kind: CopsNamespace
    plural: copsnamespaces
    singular: copsnamespace
    shortNames:
      - cns
  