name: 'release'
on:
  push:
    branches:
    - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: helm
          package-name: cops-controller          
          extra-files: |
            deployment/cops-controller/Chart.yaml
            deployment/cops-controller/values.yaml
      - name: Login to Docker Hub
        if: ${{ steps.release.outputs.release_created }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & Push Docker image
        if: ${{ steps.release.outputs.release_created }}
        run: |
          docker build . --file Dockerfile --tag conplementag/cops-controller:v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}
          docker push conplementag/cops-controller:v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}
      - name: Install Helm
        if: ${{ steps.release.outputs.release_created }}
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1
      - name: Run chart-releaser
        if: ${{ steps.release.outputs.release_created }}
        uses: helm/chart-releaser-action@v1.4.0
        with: 
          charts_dir: deployments
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: false
  

