name: release
on:
  push:
    branches:
    - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: helm
          package-name: cops-controller
          extra-files: |
            deployment/cops-controller/Chart.yaml
            deployment/cops-controller/values.yaml
      - name: Login to Docker Hub
        if: ${{ steps.release.outputs.release_created }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & Push Docker image
        if: ${{ steps.release.outputs.release_created }}
        run: |
          docker build . --file Dockerfile --tag conplementag/cops-controller:v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}
          docker push conplementag/cops-controller:v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}
      - name: Download chart releaser
        if: ${{ steps.release.outputs.release_created }}
        run: |
          curl -sSLo hcr.tar.gz "https://github.com/pete911/hcr/releases/download/v0.0.5/hcr_0.0.5_linux_amd64.tar.gz"
          tar -xzf hcr.tar.gz
          rm -f hcr.tar.gz
      - name: Package and release chart
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git config user.email "gh-action@users.noreply.github.com"
          git config user.name "gh-action"
          ./hcr -token "${{ secrets.GITHUB_TOKEN }}" -charts-dir deployment/cops-controller